In [1]:
# numpy do not copy array elements 
import numpy as np 

In [15]:
# create an array for 12 elements 
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# now change the elements 5 through 8 (excluding 8) using slice to assign a value of 12 to all those elements 
arr[5:8] = 12

In [9]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11])

In [13]:
new_arr_no_copy = arr[5:8]
new_arr_no_copy[0] = 64 
arr

array([ 0,  1,  2,  3,  4, 64, 12, 12,  8,  9, 10, 11])